"""add delivery fields to orders

Revision ID: 318982aa0b1f
Revises: 882cdf71ff65
Create Date: 2026-03-19 23:01:09.124133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318982aa0b1f'
down_revision: Union[str, Sequence[str], None] = '882cdf71ff65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_name', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_notes')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'delivery_phone')
    op.drop_column('orders', 'delivery_name')
    # ### end Alembic commands ###
