"""add mpesa fields and community posts

Revision ID: 882cdf71ff65
Revises: 
Create Date: 2026-03-19 14:58:49.356358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882cdf71ff65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.add_column('orders', sa.Column('mpesa_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'checkout_request_id')
    op.drop_column('orders', 'payment_phone')
    op.drop_column('orders', 'mpesa_code')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_table('community_posts')
    # ### end Alembic commands ###
