"""guest checkout and set password token

Revision ID: a8bfe57bf672
Revises: 318982aa0b1f
Create Date: 2026-03-24 18:27:22.499378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bfe57bf672'
down_revision: Union[str, Sequence[str], None] = '318982aa0b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('set_password_token', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('set_password_token_exp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'set_password_token_exp')
    op.drop_column('users', 'set_password_token')
    # ### end Alembic commands ###
