"""add delivery fields to orders

Revision ID: e8c459f7c10d
Revises: a8bfe57bf672
Create Date: 2026-03-25 18:20:11.026277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c459f7c10d'
down_revision: Union[str, Sequence[str], None] = 'a8bfe57bf672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_email', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_email')
    # ### end Alembic commands ###
